/**
 * @file cont.h
 * @brief NUMA CONT kernel interface (thin wrapper around CPY)
 * 
 * CONT operations ensure tensor data is stored contiguously in memory.
 * This implementation provides a thin wrapper around the sophisticated CPY kernel.
 * 
 * @author David Sanftenberg
 * @date 2024
 */

#pragma once

#include "numa-kernels.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief NUMA CONT kernel execution function (thin wrapper around CPY)
 * 
 * @param work_context Tensor to process (cast to ggml_tensor*)
 * @param params Compute parameters with thread info
 * @return GGML_STATUS_SUCCESS on success, error code on failure
 */
enum ggml_status ggml_numa_kernel_cont_execute(void * work_context, struct ggml_compute_params * params);

// ============================================================================
// Registration Functions (Auto-generated by NUMA_KERNEL_REGISTER_METADATA macro)
// ============================================================================

/**
 * @brief Query function for CONT strategy selection (auto-generated)
 */
ggml_numa_execution_strategy_t ggml_numa_kernel_cont_query(const struct ggml_tensor * tensor);

/**
 * @brief Work buffer calculation function for CONT (auto-generated)
 */
size_t ggml_numa_kernel_cont_work_buffer_calc(const struct ggml_tensor * tensor, int total_numa_nodes, int total_threads);

/**
 * @brief Registration function for CONT kernel (auto-generated)
 */
ggml_numa_kernel_registration_info_t ggml_numa_kernel_cont_register(void);

#ifdef __cplusplus
}
#endif
