/**
 * @file get_rows.h
 * @brief NUMA-aware GET_ROWS kernel header
 * @author David Sanftenberg
 */

#pragma once

#ifndef GGML_NUMA_KERNEL_GET_ROWS_H
#define GGML_NUMA_KERNEL_GET_ROWS_H

#include "numa-kernels.h"
#include "../ggml-impl.h"
#include <stdint.h>

// Function declarations - these match the functions generated by NUMA_KERNEL_REGISTER_METADATA macro

/**
 * @brief Execute GET_ROWS operation with NUMA awareness
 * @param work_context Tensor context (destination tensor)
 * @param params Compute parameters with thread info
 * @return GGML_STATUS_SUCCESS on success
 */
enum ggml_status ggml_numa_kernel_get_rows_execute(void * work_context, struct ggml_compute_params * params);

/**
 * @brief Query strategy for GET_ROWS operation based on tensor size
 * @param tensor The destination tensor to analyze 
 * @return Optimal execution strategy
 */
ggml_numa_execution_strategy_t ggml_numa_kernel_get_rows_query(const struct ggml_tensor * tensor);

/**
 * @brief Calculate work buffer requirements for GET_ROWS operation
 * @param tensor The destination tensor
 * @param total_numa_nodes Total NUMA nodes available
 * @param total_threads Total threads for execution
 * @return Required work buffer size in bytes (0 for no buffer needed)
 */
size_t ggml_numa_kernel_get_rows_work_buffer_calc(const struct ggml_tensor * tensor, int total_numa_nodes, int total_threads);

/**
 * @brief Register GET_ROWS kernel with NUMA system
 * @return Kernel registration information structure
 */
ggml_numa_kernel_registration_info_t ggml_numa_kernel_get_rows_register(void);

#endif // GGML_NUMA_KERNEL_GET_ROWS_H
