/**
 * @file mul_mat_id.h
 * @brief NUMA-aware matrix multiplication ID kernel interface
 * @author David Sanftenberg
 * 
 * This header defines the interface for the MUL_MAT_ID NUMA kernel,
 * which implements Expert-based matrix multiplication with ID-based matrix selection.
 */

#ifndef GGML_NUMA_KERNEL_MUL_MAT_ID_H
#define GGML_NUMA_KERNEL_MUL_MAT_ID_H

#include "numa-kernels.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Execute function for MUL_MAT_ID NUMA kernel
 * 
 * Performs expert-based matrix multiplication: dst = src0[expert_id] @ src1
 * where expert_id is selected from the ids tensor.
 * 
 * @param work_context The tensor being computed (destination tensor)
 * @param params Compute parameters including thread context
 * @return GGML_STATUS_SUCCESS on success, error code on failure
 */
enum ggml_status ggml_numa_kernel_mul_mat_id_execute(void * work_context, struct ggml_compute_params * params);

// ============================================================================
// Registration Functions (Auto-generated by NUMA_KERNEL_REGISTER_METADATA macro)
// ============================================================================

/**
 * @brief Query function for MUL_MAT_ID strategy selection (auto-generated)
 */
ggml_numa_execution_strategy_t ggml_numa_kernel_mul_mat_id_query(const struct ggml_tensor * tensor);

/**
 * @brief Work buffer calculation function for MUL_MAT_ID (auto-generated)
 */
size_t ggml_numa_kernel_mul_mat_id_work_buffer_calc(const struct ggml_tensor * tensor, 
                                                    int total_numa_nodes, 
                                                    int total_threads);

/**
 * @brief Registration function for MUL_MAT_ID kernel (auto-generated)
 */
ggml_numa_kernel_registration_info_t ggml_numa_kernel_mul_mat_id_register(void);

#ifdef __cplusplus
}
#endif

#endif // GGML_NUMA_KERNEL_MUL_MAT_ID_H
